---
- name: install distributive, health check packages for current role
  become: yes
  yum:
    state: present
    name: "{{ item }}"
  tags:
    - distributive
    - bootstrap
  with_items:
    - "{{ distributive_package }}"
    - "distributive-{{ current_role }}-{{ checklist_versions[current_role] }}"
    - "https://bintray.com/artifact/download/siddharthist/mantl-testing/distributive-{{ current_role }}-consul-config-{{ consul_config_versions[current_role] }}.x86_64.rpm"
    #- "distributive-{{ current_role }}-consul-config-{{ consul_config_versions[current_role] }}"
