---
- name: create system kubernetes groups
  sudo: yes
  group:
    name: kube
    state: present
    system: yes
  tags:
    - secrets
    - kubernetes

- name: add default user to kubernetes group
  sudo: yes
  user:
    name: "{{ ansible_ssh_user }}"
    system: yes
    groups: "kube"
  tags:
    - secrets
    - kubernetes

- name: create cloud provider config
  sudo: yes
  template:
    src: cloud-config.j2
    dest: "{{ cloud_provider_config }}"
    owner: root
    group: root
    mode: 0644
  when: enable_cloud_provider and cloud_provider == "openstack"
  tags:
    - secrets
    - kubernetes
