---
- name: install traefik-dynamic
  sudo: yes
  yum:
    name: "{{ traefik_package }}"
    state: present
  tags:
    - traefik
    - bootstrap

- name: write traefik config vars to the consul k/v
  run_once: yes
  command: >
    consul-cli kv-write
    {% if consul_acl_master_token is defined %}
    --token={{ consul_acl_master_token }}
    {% endif %}
    config/traefik/{{ item.path }}
    {{ item.value }}
  with_items: "{{ traefik_configuration }}"
  tags:
    - consul
    - traefik

- name: create directory for local traefik service override
  sudo: yes
  file:
    dest: /etc/systemd/system/traefik.service.d
    state: directory
    mode: 0755
  tags:
    - traefik
    - bootstrap

- name: create local traefik service override
  sudo: yes
  template:
    src: marathon.conf.j2
    dest: /etc/systemd/system/traefik.service.d/marathon.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart traefik
  tags:
    - traefik

- name: generate traefik consul service
  sudo: yes
  copy:
    src: 'traefik-consul.json'
    dest: '/etc/consul/traefik.json'
  notify:
    - reload consul
  tags:
    - traefik
